import './globals.css';
import { Inter } from 'next/font/google';
import { Poppins } from 'next/font/google';
import Header from '../components/Header';
import { UserContextProvider } from '../context/user';

const inter = Inter({ subsets: ['latin'] })
const poppins = Poppins({ subsets: ['latin'], weight: ['400', '600'] })

export const metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

export default function RootLayout({
	children,
	}: {
		children: React.ReactNode
	}) {
	return (
		<html lang="en">
	  		<body className={poppins.className}>
			  	<UserContextProvider>
					<Header />
					<main className=" py-10">
						<div className="container max-w-8xl">
							{children}
						</div>
					</main>
				</UserContextProvider>
			</body>
		</html>
  	)
}
